# Generated by Django 3.2.3 on 2021-06-08 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.DurationField(blank=True, verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipeingredientrelation',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ингредиент'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeingredientrelation',
            name='recipe',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт'),
            preserve_default=False,
        ),
    ]
