# Generated by Django 3.2.3 on 2021-06-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(help_text='Не более 100 символов', max_length=100, verbose_name='Название'),
        ),
    ]
