# Generated by Django 3.2.3 on 2021-06-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210608_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.DurationField(default=20, verbose_name='Время приготовления'),
        ),
    ]
