# Generated by Django 3.2.3 on 2021-06-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210607_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.ManyToManyField(related_name='measure', through='recipes.IngredientMeasureRelation', to='recipes.Measure', verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='title',
            field=models.CharField(help_text='Не более 40 символов', max_length=40, verbose_name='Название'),
        ),
    ]
