# Generated by Django 3.2.3 on 2021-06-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Добавьте ингредиенты.', related_name='recipes', through='recipes.RecipeIngredientRelation', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
