# Generated by Django 3.2.3 on 2021-06-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.DurationField(blank=True, null=True, verbose_name='Время приготовления'),
        ),
    ]
