# Generated by Django 3.2.3 on 2021-06-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210607_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measure',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measure',
            field=models.ForeignKey(default=87, on_delete=django.db.models.deletion.CASCADE, related_name='measure', to='recipes.measure', verbose_name='Единицы измерения'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IngredientMeasureRelation',
        ),
    ]
