# Generated by Django 3.2.3 on 2021-06-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='test_data',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Добавьте ингредиенты.', related_name='ingredient', through='recipes.RecipeIngredientRelation', to='recipes.Ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.PositiveIntegerField(default=1, verbose_name='Время приготовления'),
            preserve_default=False,
        ),
    ]
