# This is a basic workflow to help you get started with Actions

name: Pycodestyle

on:
  push:
    branches:
      - master
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        # обновление pip
        python -m pip install --upgrade pip
        # установка pycodestyle
        pip install pycodestyle
        # установка зависимостей
        pip install -r requirements.txt

    - name: Test with flake8 and django tests
      run: |
        # запуск проверки проекта по flake8
        pycodestyle api
        pycodestyle recipes
        pycodestyle users

#        # запустить написанные разработчиком тесты
#        pytest
